### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by neilrush** [kremerben/haiku_api#2]
Any request to the API returns internal server error.
![Screenshot_20211108-073131](https://user-images.githubusercontent.com/31221793/140750714-011788de-de0a-45bf-8489-d947a0b29842.png)

**Comment by neilrush** [comment]
Seems like the datamuse API is the cause.
[https://api.datamuse.com/words?ml=ringing+in+the+ears](https://api.datamuse.com/words?ml=ringing+in+the+ears)
![Screenshot_20211108-074300.png](https://user-images.githubusercontent.com/31221793/140752721-d8f5f30c-bf3a-438e-9636-89ae369b8cd0.png)

**Comment by kremerben** [comment]
Thanks for the investigation, I should add some error checking in the workflow.
